modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://github.com/shedaniel/RoughlyEnoughItems/issues"
logoFile="icon.png"
authors="shedaniel"
license="MIT"
[[mods]]
    modId="roughlyenoughitems"
    version="${version}"
    displayName="Roughly Enough Items"
    description='''
To allow players to view items and recipes.
'''

[[dependencies.lightoverlay-forge]]
    modId="cloth-config2"
    mandatory=true
    versionRange="[4.0.1,)"
    ordering="NONE"
    side="CLIENT"